apiVersion: v1
kind: ConfigMap
metadata:
  name: jw238dns-config
  namespace: default
  labels:
    app: jw238dns
data:
  config.yaml: |
    records:
      - name: example.com.
        type: A
        ttl: 300
        value:
          - 192.168.1.1
          - 192.168.1.2

      - name: example.com.
        type: AAAA
        ttl: 300
        value:
          - "2001:db8::1"

      - name: www.example.com.
        type: CNAME
        ttl: 3600
        value:
          - example.com.

      - name: example.com.
        type: MX
        ttl: 3600
        value:
          - "10 mail.example.com."
          - "20 mail2.example.com."

      - name: example.com.
        type: TXT
        ttl: 300
        value:
          - "v=spf1 include:_spf.example.com ~all"

      - name: example.com.
        type: NS
        ttl: 86400
        value:
          - ns1.example.com.
          - ns2.example.com.

      - name: _sip._tcp.example.com.
        type: SRV
        ttl: 300
        value:
          - "10 60 5060 sip.example.com."

      - name: 1.1.168.192.in-addr.arpa.
        type: PTR
        ttl: 3600
        value:
          - example.com.

      - name: example.com.
        type: SOA
        ttl: 86400
        value:
          - "ns1.example.com. admin.example.com. 2026021201 3600 900 604800 86400"

      - name: example.com.
        type: CAA
        ttl: 3600
        value:
          - "0 issue letsencrypt.org"
